In [1]:
from llama_index.llms.openai import OpenAI
from llama_index.core.agent import ReActAgent
from llama_index.core.workflow import Context

In [2]:
import llama_index.core.agent
print(dir(llama_index.core.agent))

['AgentChatResponse', 'AgentInput', 'AgentOutput', 'AgentStream', 'AgentStreamStructuredOutput', 'AgentWorkflow', 'BaseWorkflowAgent', 'CodeActAgent', 'FunctionAgent', 'ReActAgent', 'ReActChatFormatter', 'ReActOutputParser', 'ToolCall', 'ToolCallResult', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'react', 'utils', 'workflow']

In [16]:
# 시도 1
try:
    from llama_index.core.agent.react import ReActAgentWorker
    print("✅ 경로 1 성공")
except ImportError as e:
    print(f"❌ 경로 1 실패: {e}")

# 시도 2
try:
    from llama_index.core.agent.react.base import ReActAgentWorker
    print("✅ 경로 2 성공")
except ImportError as e:
    print(f"❌ 경로 2 실패: {e}")

# 시도 3
try:
    from llama_index.agent.react import ReActAgentWorker
    print("✅ 경로 3 성공")
except ImportError as e:
    print(f"❌ 경로 3 실패: {e}")

# 시도 4 - ReActAgent만 직접 사용
try:
    from llama_index.core.agent import ReActAgent
    print("✅ ReActAgent 사용 가능")
    print("사용 가능한 메서드:", [m for m in dir(ReActAgent) if not m.startswith('_')])
except ImportError as e:
    print(f"❌ ReActAgent 실패: {e}")

❌ 경로 1 실패: cannot import name 'ReActAgentWorker' from 'llama_index.core.agent.react' (/home/hojin/airflow-env/lib/python3.12/site-packages/llama_index/core/agent/react/__init__.py)
❌ 경로 2 실패: No module named 'llama_index.core.agent.react.base'
❌ 경로 3 실패: No module named 'llama_index.agent'
✅ ReActAgent 사용 가능
사용 가능한 메서드: ['add_step', 'aggregate_tool_results', 'call_tool', 'construct', 'copy', 'dict', 'events', 'finalize', 'from_orm', 'get_prompts', 'get_tools', 'handle_tool_call_results', 'init_run', 'json', 'model_computed_fields', 'model_config', 'model_construct', 'model_copy', 'model_dump', 'model_dump_json', 'model_extra', 'model_fields', 'model_fields_set', 'model_json_schema', 'model_parametrized_name', 'model_post_init', 'model_rebuild', 'model_validate', 'model_validate_json', 'model_validate_strings', 'parse_agent_output', 'parse_file', 'parse_obj', 'parse_raw', 'run', 'run_agent_step', 'schema', 'schema_json', 'setup_agent', 'start_event_class', 'stop_event_class', 'take_step', 'update_forward_refs', 'update_prompts', 'validate', 'validate_formatter', 'validate_tools']

In [1]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('/mnt/c/Users/hojin/OneDrive/바탕 화면/Kaggle/PitWall-AI/data/f1_data.db')

In [3]:
# 1. 2025년 라스베이거스에 어떤 데이터가 있는지 확인
query = "SELECT Driver, Compound, COUNT(*) as Laps, ROUND(AVG(LapTime_Sec), 3) as Avg_Pace FROM lap_times WHERE RaceID LIKE '%Las_Vegas%' AND RaceID NOT LIKE '%Practice%' AND RaceID NOT LIKE '%Qualifying%' AND IsAccurate = 1 GROUP BY Driver, Compound ORDER BY Driver;"
df = pd.read_sql_query(query, conn)

In [ ]:
df

In [5]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('/mnt/c/Users/hojin/OneDrive/바탕 화면/Kaggle/PitWall-AI/data/f1_data.db')
query = "SELECT * FROM race_results WHERE Year = 2026"
df = pd.read_sql_query(query, conn)
df

,RaceID,Year,Circuit,Driver,TeamName,Position,GridPosition,Points,Status
0,Australian Grand Prix,2026,Melbourne,RUS,Mercedes,1.0,1.0,25.0,Finished
1,Australian Grand Prix,2026,Melbourne,ANT,Mercedes,2.0,2.0,18.0,Finished
2,Australian Grand Prix,2026,Melbourne,LEC,Ferrari,3.0,4.0,15.0,Finished
3,Australian Grand Prix,2026,Melbourne,HAM,Ferrari,4.0,7.0,12.0,Finished
4,Australian Grand Prix,2026,Melbourne,NOR,McLaren,5.0,6.0,10.0,Finished
5,Australian Grand Prix,2026,Melbourne,VER,Red Bull Racing,6.0,20.0,8.0,Finished
6,Australian Grand Prix,2026,Melbourne,BEA,Haas F1 Team,7.0,12.0,6.0,Lapped
7,Australian Grand Prix,2026,Melbourne,LIN,Racing Bulls,8.0,9.0,4.0,Lapped
8,Australian Grand Prix,2026,Melbourne,BOR,Audi,9.0,10.0,2.0,Lapped
9,Australian Grand Prix,2026,Melbourne,GAS,Alpine,10.0,14.0,1.0,Lapped
10,Australian Grand Prix,2026,Melbourne,OCO,Haas F1 Team,11.0,13.0,0.0,Lapped
11,Australian Grand Prix,2026,Melbourne,ALB,Williams,12.0,15.0,0.0,Lapped
12,Australian Grand Prix,2026,Melbourne,LAW,Racing Bulls,13.0,8.0,0.0,Lapped
13,Australian Grand Prix,2026,Melbourne,COL,Alpine,14.0,16.0,0.0,Lapped
14,Australian Grand Prix,2026,Melbourne,SAI,Williams,15.0,21.0,0.0,Lapped
15,Australian Grand Prix,2026,Melbourne,PER,Cadillac,16.0,18.0,0.0,Lapped
16,Australian Grand Prix,2026,Melbourne,STR,Aston Martin,17.0,22.0,0.0,Lapped
17,Australian Grand Prix,2026,Melbourne,ALO,Aston Martin,18.0,17.0,0.0,Retired
18,Australian Grand Prix,2026,Melbourne,BOT,Cadillac,19.0,19.0,0.0,Retired
19,Australian Grand Prix,2026,Melbourne,HAD,Red Bull Racing,20.0,3.0,0.0,Retired
20,Australian Grand Prix,2026,Melbourne,PIA,McLaren,21.0,5.0,0.0,Did not start
21,Australian Grand Prix,2026,Melbourne,HUL,Audi,22.0,11.0,0.0,Did not start

In [2]:
query = "SELECT * FROM race_results WHERE Year = 2026"

In [3]:
df = pd.read_sql_query(query, conn)

In [4]:
df

,RaceID,Year,Circuit,Driver,TeamName,Position,GridPosition,Points,Status
0,Australian Grand Prix,2026,Melbourne,RUS,Mercedes,1.0,1.0,25.0,Finished
1,Australian Grand Prix,2026,Melbourne,ANT,Mercedes,2.0,2.0,18.0,Finished
2,Australian Grand Prix,2026,Melbourne,LEC,Ferrari,3.0,4.0,15.0,Finished
3,Australian Grand Prix,2026,Melbourne,HAM,Ferrari,4.0,7.0,12.0,Finished
4,Australian Grand Prix,2026,Melbourne,NOR,McLaren,5.0,6.0,10.0,Finished
5,Australian Grand Prix,2026,Melbourne,VER,Red Bull Racing,6.0,20.0,8.0,Finished
6,Australian Grand Prix,2026,Melbourne,BEA,Haas F1 Team,7.0,12.0,6.0,Lapped
7,Australian Grand Prix,2026,Melbourne,LIN,Racing Bulls,8.0,9.0,4.0,Lapped
8,Australian Grand Prix,2026,Melbourne,BOR,Audi,9.0,10.0,2.0,Lapped
9,Australian Grand Prix,2026,Melbourne,GAS,Alpine,10.0,14.0,1.0,Lapped
10,Australian Grand Prix,2026,Melbourne,OCO,Haas F1 Team,11.0,13.0,0.0,Lapped
11,Australian Grand Prix,2026,Melbourne,ALB,Williams,12.0,15.0,0.0,Lapped
12,Australian Grand Prix,2026,Melbourne,LAW,Racing Bulls,13.0,8.0,0.0,Lapped
13,Australian Grand Prix,2026,Melbourne,COL,Alpine,14.0,16.0,0.0,Lapped
14,Australian Grand Prix,2026,Melbourne,SAI,Williams,15.0,21.0,0.0,Lapped
15,Australian Grand Prix,2026,Melbourne,PER,Cadillac,16.0,18.0,0.0,Lapped
16,Australian Grand Prix,2026,Melbourne,STR,Aston Martin,17.0,22.0,0.0,Lapped
17,Australian Grand Prix,2026,Melbourne,ALO,Aston Martin,18.0,17.0,0.0,Retired
18,Australian Grand Prix,2026,Melbourne,BOT,Cadillac,19.0,19.0,0.0,Retired
19,Australian Grand Prix,2026,Melbourne,HAD,Red Bull Racing,20.0,3.0,0.0,Retired
20,Australian Grand Prix,2026,Melbourne,PIA,McLaren,21.0,5.0,0.0,Did not start
21,Australian Grand Prix,2026,Melbourne,HUL,Audi,22.0,11.0,0.0,Did not start

In [1]:
from dotenv import load_dotenv
import os


GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")

In [2]:
import google.generativeai as genai
import os

genai.configure(api_key=os.getenv("GOOGLE_API_KEY"))

# 사용 가능한 embedding 모델 목록 출력
for model in genai.list_models():
    if 'embedContent' in model.supported_generation_methods:
        print(f"✅ {model.name}")

✅ models/gemini-embedding-001

In [25]:
# 간단한 테스트
import os
from llama_index.embeddings.google_genai import GoogleGenAIEmbedding

api_key = os.getenv("GOOGLE_API_KEY")
embed_model = GoogleGenAIEmbedding(
    model_name="models/gemini-embedding-001",
    api_key=api_key
)

# 테스트
result = embed_model.get_text_embedding("hello world")
print(f"임베딩 차원: {len(result)}")  # 768 나오면 성공

임베딩 차원: 3072

In [7]:
from llama_index.llms.google_genai import GoogleGenAI

from llama_index.core import Settings
from llama_index.embeddings.google_genai import GoogleGenAIEmbedding
from llama_index.llms.google_genai import GoogleGenAI

# API 키 가져오기 (Secrets or Env)
api_key = os.getenv("GOOGLE_API_KEY")

# 1. LLM 강제 설정 (Gemini)
Settings.llm = GoogleGenAI(
    model="models/gemini-2.5-flash", 
    api_key=api_key
)